parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
env:
  node: true
  es6: true
extends:
  - eslint:recommended
  - prettier
rules:
  no-console:
    - warn
    - allow:
        - warn
        - error
